# Experiment details
EXPName: Nebraska Mead Site
Region: Nebraska
code: NE
Fields_of_Interest: ./NE_site/NE_site.shp
Processed_Info:     # leave empty


# Model details
EPICModel: ./model/EPIC2301dt20230820
start_year: 1995
duration: 25
output_types:
  - ACY  # Annual Crop data file
  - DGN  # Daily general output file
log_dir: ./log
output_dir: ./output # if empty, Output files from epic runs are not saved (To save space use post_process options).


# Weather configuration
weather:
  dir: ./weather
  start_date: 1981-01
  end_date: 2020-12
  offline: false  # if true, weather info is downloaded from daymet before runs (To save space leave it false).
  primary_source: daymet # daymet, gridmet, NLDAS, ERA5 (Only daymet works for now.)

# Soil details
soil:
  ssurgo_gdb: ./soil/gSSURGO_NE.gdb
  soil_map: /home/chandrab/GeoEPIC_metadata/SSURGO.tif
  files_dir:  #if soil files directory is specified, processing gdb file is skipped.

# Info for Sit files
site:
  dir: ./sites
  slope: /home/chandrab/GeoEPIC_metadata/slope_us.tif
  elevation: /home/chandrab/GeoEPIC_metadata/SRTM_1km_US_project.tif
  slope_length: ./soil/NE_slopelen.csv


# OPC details
opc_dir: ./opc
opc_prefix: CropRot


# Run params
select: Random(0.1) # Range(0.35, 0.8), Random(0.1) or a expression to select csbs with specific property. ex: CNTYFIPS == 8; Shape_Area > 6
num_of_workers: 40 # No. of parellel processes. Should be less than number of cpu cores.
timeout: 10 # No. of seconds to let a simulation run. Execution is terminated after timeout.

# Post Process
process_outputs: ./utils.py reduce_outputs # if not empty during runs, output processing is also carried out.
visualize: ./utils.py spatial_plot # specify function to visualize the required results
