### Site metadata ###

site_name: EPIC package
site_description: Python Utility function to run EPIC model
site_url: https://smarsGroup.github.io/EPIC-pkg/

repo_url: https://github.com/smarsGroup/EPIC-pkg

### Build settings ###

theme: readthedocs

nav:
  - Home: index.md