### Site metadata ###

site_name: EPIC package
site_description: Python Utility function to run EPIC model
site_url: https://smarsgroup.github.io/EPIC-pkg/

repo_url: https://github.com/smarsGroup/EPIC-pkg

### Build settings ###

theme: readthedocs

nav:
  - Home: index.md
  - Crop Sequence Boundaries: csb.md
  - EPIC model: epic.md
  - Weather: Weather.md
  - Soil: Soil.md
  - Crop Management Info: OPC.md
  - Quick Start Guide: runexp.md
  - API: api.md
